### ISSUE TITLE
Upgrade gitlab

### ISSUE THREAD

**Issue by Fridus** [lwolf/kubernetes-gitlab#1]
Hi,

Could you say me the correct procedure to upgrade gitlab or runner ?

Thx,
Regards

**Comment by lwolf** [comment]
Hi,
Just like with any kubernetes deployment you can edit deployment file and apply changes.
```
$ vim gitlab/deployment.yml 
...
image: sameersbn/gitlab:8.12.7 -> image: sameersbn/gitlab:8.12.8
...
$ kubectl apply -f deployment.yml
```

or you can change image version directly with `kubectl edit` command:
```
kubectl edit deploy/gitlab
```

**Comment by lwolf** [comment]
No problem :)
Update of the deployment will do pull/stop/start of the container, just like in that manual.
Migration is handled in the `sameersbn/docker-gitlab` container.
Make sure to make a backup of the DB if you need.
