### ISSUE TITLE
I have a question about "assuming that DNS is properly configured"

### ISSUE THREAD

**Issue by pjatacsukb** [lwolf/kubernetes-gitlab#4]
Hello!
I configured our local DNS server to point the "gitlab.example.com" like domain to one of the worker nodes.
But this doesn't seems to be a good method. 
Do I need an external NGINX that load balances the domain "gitlab.example.com" across all worker nodes?
Or where do I have to point the "gitlab.example.com" like domain record?
Thank you for your answer,
Bence

**Comment by lwolf** [comment]
Hi,
If you have deployed ingress rules and load balancer (inside kubernetes) pointing your DNS to the node should be enough.

**Comment by lwolf** [comment]
Is your cluster created with kubeadm?

I just remembered that I had troubles with ingress a few days ago on the cluster created with kubeadm.

**Comment by pjatacsukb** [comment]
Thank you for your answers!
We are using Tectonic with Kubernetes. 
The Ingress is working I think, I pointed the domain to one of the worker nodes.
Does Ingress load balances across all nodes when I point the domain to one of the worker nodes?

**Comment by lwolf** [comment]
Yes, ingress load balancer should run on all worker nodes.
What I can suggest is to check 
* check that ingresses were actually created `kubectl get ing --all-namespaces`
* check that 80/443 ports are actually open on worker nodes
* status and logs of `tectonic-ingress-controller` pods

**Comment by pjatacsukb** [comment]
It works, im still figuring out Ingress, thank you for your answers!
