### ISSUE TITLE
Username root  and Password  is Invalid

### ISSUE THREAD

**Issue by LLitchi** [lwolf/kubernetes-gitlab#5]
I do not change any thing ,but when i sign in, Invalid Login or password.

**Comment by lwolf** [comment]
Is there anything in the logs? It could be problems with running migrations.
`kubectl logs -f gitlab-<pod-id> --namespace=gitlab`

**Comment by LLitchi** [comment]
Then I try to modify the value of GITLAB_ROOT_PASSWORD in gitlab-deployment.yml, there is no problem
