### ISSUE TITLE
First login new root password failure

### ISSUE THREAD

**Issue by bobuntu** [lwolf/kubernetes-gitlab#6]
### Expected Behavior
On first root login, new password should be accepted.
### Actual Behavior
[screenshot](https://imgur.com/a/9eBPG)
### Attempts to correct the issue
1. Delete all running containers and apply the manifests with the following tweaks:
    * without `GITLAB_ROOT_PASSWORD`. No change in behavior.
    * with a different `GITLAB_ROOT_PASSWORD`. No change in behavior.
2. `docker exec --user git -it <container-id> bundle exec rake gitlab:setup RAILS_ENV=production` does a lot of things, asks me if I'm OK to wipe the database and build a fresh one. Once I agree it goes on with its lots and in the end a green message: user `root` has been created, password will be added on first login. But the actual behavior is unchanged: **7 errors prohibited this user from being saved** same as before the attempt.
### What I suspect the root cause could be
1. The webserver ignores the rake task, and so it keeps serving the "create new password" page. Should I purge the cache? **How**?
-OR-
2. The change password token generator is at fault or ignores the rake task.
3. This `kubectl logs -f gitlab-azAZ09 --namespace gitlab`:
```
Configuring nginx...
Configuring nginx::gitlab...
Setting up GitLab for firstrun. Please be patient, this could take a while...
Missing Rails.application.secrets.jws_private_key for production environment. The secret will be generated and stored in config/secrets.yml.
gitlab-devops already exists
Migrating database...
Clearing cache...
```
### Environment
k8s v1.7.8
sameersbn/gitlab:10.0.3

Cc @lwolf

**Comment by lwolf** [comment]
Hi.
Sorry for the late reply.
I have finally found time to try it.
The issue you're seeing is that database migrations are failing to apply during the first.
And there is no error, even with debug logging.

But when I tried to  `kubectl exec it <container-id> bundle exec rake gitlab:setup RAILS_ENV=production` I actually got an error.

```
== Seed from /home/git/gitlab/db/fixtures/production/001_admin.rb
Could not create the default administrator account:

--> Password is too short (minimum is 8 characters)
```

After I deleted everything, set the password to some long random string, everything installed just fine and I was able to login.

**Comment by bobuntu** [comment]
Thanks @lwolf. I did try that too, though I must admit I wasn't using a long string. If you don't mind, what do you mean by "after I deleted everything" in your comment (last paragraph)?...

**Comment by lwolf** [comment]
`kubectl delete ` all persistent entities, like gitlab, postgres,redis.
 In my case, I just deleted entire namespace.

**Comment by bobuntu** [comment]
It worked! All I did was use `kubectl exec` instead of `docker exec`.
