### ISSUE TITLE
Pod spec needs to be updated to run properly

### ISSUE THREAD

**Issue by mateothegreat** [lwolf/kubernetes-gitlab#7]
Pod spec needs to be updated to run properly..
```
        command: ["/usr/bin/minio"]
        args:
            - server
            - minio-0.default.svc.cluster.local:9000/data
            - minio-1.default.svc.cluster.local:9000/data
            - minio-2.default.svc.cluster.local:9000/data
            - minio-3.default.svc.cluster.local:9000/data
```
(see https://github.com/mateothegreat/k8-byexamples-minio/blob/master/manifests/statefulset.yaml#L26):

**Comment by lwolf** [comment]
PRs are welcome, but the most up-to-date version of this manifests are available as a chart https://github.com/lwolf/gitlab-chart
